--first, remove the table if it exists
drop table if exists bookmarks;

--create table a new
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text not null,
    url text not null,
    description text,
    rating integer
);

--insert some test data
--using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
    values 
    ('google', 'http://google.com', 'google site', 4),
    ('thinkful', 'http://thinkful.com', 'thinkful site', 5),
    ('amazon', 'http://amazon.com', 'amazon site', 3),
    ('youtube', 'http://youtube.com', 'youtube site', 4),
    ('github', 'http://github.com', 'github site', 5),
    ('linkedIn', 'http://linkedin.com', 'linkedin site', 5),
    ('naver', 'http://naver.com', 'naver site', 3),
    ('w3schools', 'http://w3schools.com', 'w3school site', 2),
    ('regexlib', 'https://regexlib.com/', 'regexlib site', 2),
    ('postgresql', 'http://postgresql.org', 'postgresql site', 4);
